local COMMON = require "libs.common"
local GUI_UTILS = require "libs.gui_utils"
local GOOEY_DL = require "gooey.themes.dirtylarry.dirtylarry"
local SM = require "libs.sm.sm"
local LEVELS = require "scenes.game.model.levels"
local FaceModel = require "common.face.face_model"
local FaceView = require "common.face.face_view"

local Script = COMMON.new_n28s()

function Script:bind_vh()
	self.vh = {
		btn_back = {name = "btn_back", root = gui.get_node("btn_back/bg")},
		btn_next = {name = "btn_next", root = gui.get_node("btn_next/bg")},
		btn_prev = {name = "btn_prev", root = gui.get_node("btn_prev/bg")},
		lbl_pages = {name = "lbl_pages", root = gui.get_node("lbl_pages")},
	}


end

function Script:init()
	self:bind_vh()
	COMMON.input_acquire()
end



function Script:update(dt)
	if COMMON.GLOBAL.DEBUG_FACES then
		gui.set_text(self.vh.lbl_pages.root,string.format("Страница: %s/%s",COMMON.GLOBAL.DEBUG_FACES.faces_page_current,COMMON.GLOBAL.DEBUG_FACES.faces_page_max))
	end
end

function Script:final()
	COMMON.input_release()
end


function Script:on_input(action_id, action)
	GOOEY_DL.button(self.vh.btn_back.name, action_id, action, function(button)
		SM:show("StartScene")
	end)
	GOOEY_DL.button(self.vh.btn_next.name, action_id, action, function(button)
		msg.post("/scene_controller#script","change_page",{value = 1})
	end)
	GOOEY_DL.button(self.vh.btn_prev.name, action_id, action, function(button)
		msg.post("/scene_controller#script","change_page",{value = -1})
	end)


end



COMMON.N28S.register(Script)