local COMMON = require "libs.common"
local GOOEY = require "gooey.themes.dirtylarry.dirtylarry"

local Script = COMMON.new_n28s()

function Script:bind_vh()
	self.vh = {}
end

function Script:init()
	self:bind_vh()
	COMMON.input_acquire()
end

function Script:update(dt)end

function Script:final()
	COMMON.input_release()
end


function Script:on_input(action_id, action)
end



COMMON.N28S.register(Script)